### ISSUE TITLE
No Hover effect on sidebar

### ISSUE THREAD

**Issue by AK4266** [group-patronage/group-patronage#1]
### What is the issue?
When ever i point my pointer to the sidebr options like all campaigns, start campaings options there isn't any over action

![Screenshot 2023-05-20 113855](https://github.com/group-patronage/group-patronage/assets/99728079/cf95efc4-a703-46ef-9b03-a38c7325c23b)

### Are you willing to work on this issue

I would be willing to work on this issue

**Comment by LakshaySK106** [comment]
hover effect must show the name of the page in uppercase following the fonts and theme used. And keeping the active status
