### ISSUE TITLE
[FEATURE] Landing Page not responsive on mobile devices

### ISSUE THREAD

**Issue by Geeta259** [group-patronage/group-patronage#105]
### Description

Landing page of website not responsive on mobile devices.
@LakshaySK106  I would like to work upon it under GSSOC'23.
![Screenshot (432)](https://github.com/group-patronage/group-patronage/assets/75520947/6bfaa852-25c1-486a-b372-6a9125d0c83f)

**Comment by LakshaySK106** [comment]
you will find the whole website is not responsive at all. you can go ahead if you would like to make all the pages responsive in terms of design. I'm assigning you this work under GSSoC and with level 3.
