### ISSUE TITLE
Campaigns created by the user is not displayed in the home page 

### ISSUE THREAD

**Issue by KandepiBhavani23** [group-patronage/group-patronage#106]
### Description

1. Even through user has created the campaigns, the campaigns are not displayed in the Dashboard Tab.
2. Created Campaigns should also be listed in All Campaigns Tab.

### Screenshots

![image](https://github.com/group-patronage/group-patronage/assets/120291769/99d4e52a-6910-4987-b051-f34e7f569970)

**Comment by KandepiBhavani23** [comment]
Please assign this issue under Gssoc'23

**Comment by LakshaySK106** [comment]
Assigned you!
