### ISSUE TITLE
Adding support for other ERC 20 tokens for donation of campaign

### ISSUE THREAD

**Issue by guha-rahul** [group-patronage/group-patronage#11]
I want the contract to be able to accept erc20 tokens other then Ethereum

**Comment by manavtore** [comment]
hello,
I am a contributor to GSSOC'23 , Can I contribute to this modification?

**Comment by Kali-Decoder** [comment]
Can i solve this issue

**Comment by LakshaySK106** [comment]
hey, you'll try to come up with the prototype at least. I'll assign this issue to the particular one, or you may work in a group.
