### ISSUE TITLE
[FEATURE] Update Readme

### ISSUE THREAD

**Issue by Shikhar9425** [group-patronage/group-patronage#120]
### Description

want to add some features

**Comment by Shikhar9425** [comment]
@LakshaySK106 please assign this issue

**Comment by LakshaySK106** [comment]
Hey, @Shikhar9425, please provide the complete description of the issue that you have created.

**Comment by Shikhar9425** [comment]
> Hey, @Shikhar9425, please provide the complete description of the issue that you have created.

I want to add some features of the project in the readme and want to make the readme more impressive

**Comment by LakshaySK106** [comment]
It's still not to the point but it's okay. You may go ahead!
