### ISSUE TITLE
Incorrect Logout Redirect URL

### ISSUE THREAD

**Issue by Nishitbaria** [group-patronage/group-patronage#122]
### Description

When logging out from the website, the current behavior is that it redirects to `127.0.0.1:5173` instead of the expected homepage URL `https://group-patronage.netlify.app/`.

Steps to Reproduce:
1. Log in to the website.
2. Perform some actions or navigate to different pages.
3. Click on the "Logout" button or trigger the logout functionality.
4. Observe the redirection URL.

Expected Behavior:
Upon logging out, the website should redirect users to the homepage URL `https://group-patronage.netlify.app/`.

Actual Behavior:
The website redirects to `127.0.0.1:5173`, which is not the expected homepage URL.

### Screenshots

https://github.com/group-patronage/group-patronage/assets/85815172/48672031-99ae-439f-b04d-6789108a87ac

### Additional information

Additional Information:
- This issue occurs consistently and is reproducible.
- The logout functionality seems to be redirecting to an incorrect URL.
- The expected behavior is to redirect users to the homepage URL `https://group-patronage.netlify.app/` upon successful logout.

Please assign me the issue and i will resolve this issue so that the logout functionality redirects users to the correct homepage URL.

**Comment by Nishitbaria** [comment]
@Nishitbaria ,please assign this issue ,i will create pull request

**Comment by Nishitbaria** [comment]
@LakshaySK106 ,please review my pull request

**Comment by LakshaySK106** [comment]
Merged, Thank you!
