### ISSUE TITLE
[style] Hovering Text of sidebar

### ISSUE THREAD

**Issue by krutikajichkar** [group-patronage/group-patronage#137]
### What's the style idea?

The text is coming on the top of logo while hovering , that should be in the left of logo , i want to change this , please assign me this under gssoc'23

![Screenshot (145)](https://github.com/group-patronage/group-patronage/assets/93243210/8f5f388d-7ae8-4add-a63f-9a003d1a29c0)

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by LakshaySK106** [comment]
Make sure to follow the latest version of the code!

**Comment by krutikajichkar** [comment]
okay @LakshaySK106
