### ISSUE TITLE
Logo in Navbar

### ISSUE THREAD

**Issue by krutikajichkar** [group-patronage/group-patronage#151]
### Description

Logo on large screen and logo on small screen differs , i want to fix this , please assign me this under gssoc'23

### Screenshots

![Screenshot (160)](https://github.com/group-patronage/group-patronage/assets/93243210/98c527d7-9636-4825-88c4-45e0aef2fa5c)

![Screenshot (159)](https://github.com/group-patronage/group-patronage/assets/93243210/1bad1f76-3c1d-41d9-8ba4-61d9e41e422b)

### Additional information

@LakshaySK106  also mention which logo to keep , the one on large screen or the one on small

**Comment by krutikajichkar** [comment]
@LakshaySK106  which logo should I keep

**Comment by LakshaySK106** [comment]
the large screen logo
