### ISSUE TITLE
Visibility of search bar

### ISSUE THREAD

**Issue by krutikajichkar** [group-patronage/group-patronage#157]
### Description

- Search bar should not be visible while creating a campaign .
- Surveys section requires search bar with " search for surveys " , right now it is showing " search for campaigns "
- I want to fix that , please assign me this under gssoc'23

**Comment by LakshaySK106** [comment]
leave the first.
You may work on second issue.

**Comment by krutikajichkar** [comment]
> leave the first. You may work on second issue.

@LakshaySK106 I didn't get it , can you please be more specific about what i have to leave and what to work on

**Comment by LakshaySK106** [comment]
keep the search bar while creating the campaign too. So, if the user wishes to search for campaigns at that moment will be redirected to allCampaign page to see the searched campaign results. So, I was asking to leave this and work on ````Surveys section requires search bar with " search for surveys " , right now it is showing " search for campaigns "````

**Comment by krutikajichkar** [comment]
okay , got it
