### ISSUE TITLE
[FEATURE] Adding create survey page

### ISSUE THREAD

**Issue by krutikajichkar** [group-patronage/group-patronage#158]
### Description

- Create a survey button is not taking anywhere while clicking on it.
- I want to add page for creating surveys.
- Please assign me this under gssoc'23

**Comment by LakshaySK106** [comment]
The feature you thought of adding is really remarkable. So, could you make sure to add all required input fields in the form like the heading, short description, tag, and deadline? For the details, you can refer to any survey card. 

Also, the page must look like as same as the create campaign page in terms of design, themes, etc.

you may take the help of fellow developers if you would like to. I'll make this issue open to contribute.

**Comment by krutikajichkar** [comment]
@LakshaySK106 got it , I will do that
