### ISSUE TITLE
Campaign form UI improvement

### ISSUE THREAD

**Issue by Geeta259** [group-patronage/group-patronage#16]
`
![Screenshot (230)](https://github.com/group-patronage/group-patronage/assets/75520947/ed74d6a2-ab28-4ffd-8539-2db5bfa1aafe)

Main heading can be better !
Hover effect can add into input field when click on it border should be highlighted.
When input field is empty danger colour red can be add into border.
Overall make better UI for this campaign form.
@LakshaySK106  , I would like to contribute on this project under GSSOC'23.

**Comment by LakshaySK106** [comment]
Sure!

**Comment by Venkatakrishnan-Ramesh** [comment]
@Geeta259 Can u kindly give us update on this issue, since its been 3 weeks already we would like to know the update from you

**Comment by Geeta259** [comment]
@Venkatakrishnan-Ramesh  Sorry to say , due to some circumstances not able to work on it . Please give me 2 or 3 days more , I'll definitely let you know if I can not able to work on it.

**Comment by Venkatakrishnan-Ramesh** [comment]
@Geeta259 Yeah we understand , please be asap

**Comment by Geeta259** [comment]
> @Geeta259 Yeah we understand , please be asap

@Venkatakrishnan-Ramesh  Please check my PR#82 I resolved this issue.

**Comment by Venkatakrishnan-Ramesh** [comment]
@Geeta259  Thank you for contribution , we are closing this issue
