### ISSUE TITLE
[style] loader position

### ISSUE THREAD

**Issue by BhartiNagpure** [group-patronage/group-patronage#165]
### What's the style idea?

We need to improve

Loader position need to be in center it  shows in left side.
I would like to fix it.
![Screenshot 2023-07-20 184707](https://github.com/group-patronage/group-patronage/assets/104631882/61ae3fa0-cb46-4bf1-8d3c-940b3e855fdf)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by LakshaySK106** [comment]
I've assigned this issue that might have been addressed previously, but I'm not certain as I don't recall the person it was assigned to. Nonetheless, I'm assigning it to you also make sure to follow the latest code.

**Comment by krutikajichkar** [comment]
@LakshaySK106 I have worked on it already , The screenshot is from the link which is on github which doesnt have new changes
