### ISSUE TITLE
Logout redirecting error  GsSoC'23

### ISSUE THREAD

**Issue by kunalkashyap-1** [group-patronage/group-patronage#17]
## Bug Description
After clicking on the "Logout" button in the sidebar, the user is logged out successfully but redirected to the wrong URL (127.0.0.1:5732) instead of the expected URL ("/").

![Screenshot from 2023-05-21 16-28-09](https://github.com/group-patronage/group-patronage/assets/91254500/347e628f-52be-462c-b15f-f274744a89f3)

 I would like to contribute on this project under GSSOC'23. @LakshaySK106

**Comment by LakshaySK106** [comment]
This issue can be resolved at my end only by just putting the correct URL in the auth0. Thank you for exploring. Try looking into other issues
