### ISSUE TITLE
Search Bar is Not Working

### ISSUE THREAD

**Issue by KandepiBhavani23** [group-patronage/group-patronage#2]
Whenever we are trying to search for the campaign names the below cards are not filtered according to the search criteria

![image](https://github.com/group-patronage/group-patronage/assets/120291769/323bd0c7-ffa4-48c3-9025-10ca9283232f)

**Comment by KandepiBhavani23** [comment]
I am willing to work on this issue

**Comment by LakshaySK106** [comment]
Assigned!

**Comment by KandepiBhavani23** [comment]
Can you please add GSSoC'23 label for this issue.
