### ISSUE TITLE
fixing the campaign deadline check

### ISSUE THREAD

**Issue by blessingblockchain** [group-patronage/group-patronage#20]
(1) In the createCampaign function, the condition campaign.deadline < block.timestamp is incorrect. It should be block.timestamp < _deadline to ensure the deadline is in the future.

(2) Integer Overflow: The amountCollected variable in the Campaign struct and the campaign.amountCollected variable in the donateToCampaign function are not protected against integer overflow. Consider using a SafeMath library to handle arithmetic operations and prevent overflow/underflow issues.

(3) Lack of Event Logging: It's a good practice to emit events for important contract state changes. Consider adding events to log campaign creations and donations, which can make it easier to track and analyze contract activity.

(4) No Validation for Campaign ID: The donateToCampaign and getDonators functions do not validate whether the provided campaign ID is valid. It's important to check if the campaign exists before performing operations on it.

(5) Gas Limit Consideration: The getCampaigns function returns an array of Campaign structs. Depending on the number of campaigns and their size, it can result in exceeding the gas limit for contract execution. Consider splitting this function into paginated or batched retrieval to avoid gas limit issues.

You wrote a briliant contract @LakshaySK106 , please assign me so i can correct possible errors
Assign me this issue @LakshaySK106

**Comment by LakshaySK106** [comment]
All the optimizations and checks were not taken into consideration while writing the contract. You may work on them. I'm assigning this task to you, ATB.
