### ISSUE TITLE
fix the deadline(days left) issue in the campaign details

### ISSUE THREAD

**Issue by LakshaySK106** [group-patronage/group-patronage#22]
problem statement: days left are going in negative numbers. It must be like when the deadline hits zero the campaign must be removed from the home page.

**Comment by trishas95** [comment]
hey @LakshaySK106 I'd be glad if you could assign this issue to me to work on.

**Comment by Venkatakrishnan-Ramesh** [comment]
hey @trishas95 . can u kindly give us the update regarding the issue status since it been 3 weeks already

**Comment by Venkatakrishnan-Ramesh** [comment]
Since there are no updates it been to pushed to no assignee. Open for contribution

**Comment by trishas95** [comment]
> hey @trishas95 . can u kindly give us the update regarding the issue status since it been 3 weeks already 

I actually had been logged out of my GitHub for over a month and due to some email complications, it was pretty difficult for me to get back in...I'll get on this issue asap
