### ISSUE TITLE
Add badges to Readme.md

### ISSUE THREAD

**Issue by Thrillseekr** [group-patronage/group-patronage#25]
I'll give a new intractive look to Readme.md
Add badges too.

Please assign this to me.

**Comment by Venkatakrishnan-Ramesh** [comment]
hey @Thrillseekr  . can u kindly give us the update regarding the issue status since it been 3 weeks already

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign
