### ISSUE TITLE
Landing Page : Improvement in UI of the landing page

### ISSUE THREAD

**Issue by astha-05** [group-patronage/group-patronage#28]
I would like to change the overall UI of the landing page along with the changes in the text with the catchy intro so that it looks appealing to the user,  increases engagement in the website and improves their experience all together.
@LakshaySK106 Please assign this issue to me under GSSOC'23

**Comment by LakshaySK106** [comment]
the landing page actually lacks a good UI. You may work on it, you're assigned!

**Comment by Mansi1236** [comment]
I'd like to work on this issue since this issue has been open since last week, if the PR by the current assigned person is not merged then can I please work on this issue?

**Comment by LakshaySK106** [comment]
No PR is yet raised for this issue. you may work on this; I've assigned you!

**Comment by astha-05** [comment]
Hey @LakshaySK106 very sorry I couldn't start working on it due to some medical emergency.  Can I still work it?

**Comment by LakshaySK106** [comment]
Hey, @astha-05 it's no worries! You both can do the collaborative work, working on implementing different features to the landing page.

**Comment by astha-05** [comment]
Okay @LakshaySK106 thank you so much for understanding. Will start working on it asap.

**Comment by astha-05** [comment]
Hey! @LakshaySK106 I went through the code base of the project and I discovered that the landing page is built using the React framework of Javascript. At present, I am yet to acquire proficiency in this framework. So I will not be able to contribute to the project. You can surely go ahead and unassign me.
Thank you for  your consideration

**Comment by Mansi1236** [comment]
I will not be able to contribute to this project. I have unassigned myself from this issue. I apologize for the inconvenience caused.
