### ISSUE TITLE
Fix Incorrect Redirection on Clicking Logout button in Dashboard.

### ISSUE THREAD

**Issue by vishnu9865** [group-patronage/group-patronage#3]
## Incorrect redirection of Logout instead of Home Page.
 - The logout button redirects to [http://127.0.0.1:5173/](http://127.0.0.1:5173/).
 - It should actually redirect to [https://group-patronage.netlify.app/](https://group-patronage.netlify.app/).

I would like to contribute to solve this issue. 
@LakshaySK106  Please assign this issue to me.
Thanks in Advance. 😊👍🏽

## Existing Logout Button:
![image](https://github.com/group-patronage/group-patronage/assets/91585213/669b1d68-bf94-4bb5-b998-f7a0b9233775)

## Redirected Page:
![image](https://github.com/group-patronage/group-patronage/assets/91585213/971035ef-78c5-4d3d-91e9-7a0302176afd)

**Comment by LakshaySK106** [comment]
This issue can be resolved at my end only by just putting the correct URL in the auth0. Thankyou for exploring. Try looking into other issues
