### ISSUE TITLE
Survey tab

### ISSUE THREAD

**Issue by Vanoita** [group-patronage/group-patronage#30]
The 'Create a new survey' button is currently not functioning. To address this issue, I propose implementing a dynamic solution by introducing a pop-up form component. This component will be activated when the user interacts with the button, enabling them to enter the required information. Once the user submits the form, the entered details will be securely stored and made accessible in the survey tab.

**Comment by LakshaySK106** [comment]
The whole survey page is static in nature. It's hardcoded; nothing is functional. Your proposal is totally acceptable once you implement it.

**Comment by LakshaySK106** [comment]
It would be best to create the component taking all the details already mentioned in the survey template.

**Comment by Venkatakrishnan-Ramesh** [comment]
hey @Vanoita  . can u kindly give us the update regarding the issue status since it been 2 weeks already

**Comment by Venkatakrishnan-Ramesh** [comment]
The issue is open for assignee , Kindly raise issue if anyone would like to contribute

**Comment by Vanoita** [comment]
I encountered a problem and contacted you on Discord. Could you please look into it?. I would like to work on this issue.
