### ISSUE TITLE
Issue related to createCampaign() function

### ISSUE THREAD

**Issue by shikhar229169** [group-patronage/group-patronage#31]
In the createCampaign() function, the owner of campaign is taken as input from user. And this can create a mess if user entered wrong address.
So I would like to make following change:

- Instead of taking owner as input, the owner should be the one who called the createCampaign() function, i.e. msg.sender

And I want to do this under GSSOC.

**Comment by LakshaySK106** [comment]
It's not taking the owner's address as input although it's taking the name of the owner while creating a new campaign. The owner's address stored will be the address of the MetaMask wallet address and it's happening. So, no issues.

You may look at fixing the issue of the deadline. When the campaign hits the deadline it should be removed from the page but it's not happening.

**Comment by shikhar229169** [comment]
Sure, I will look into this.
But before that I actually forgot to add a check in make donations function, which will revert the call if campaign time is exceeded and if there is any new improvement required, I will check for that too.
Also should I write test for the contract, like the unit test and staging test.

**Comment by shikhar229169** [comment]
And one more thing in the donate function, the one who calls should not be the owner of the campaign.
