### ISSUE TITLE
add tech stacks and badges(shields)

### ISSUE THREAD

**Issue by mridulsaggi** [group-patronage/group-patronage#35]
i would like to add the tech stack shields in the readme file.
this will give a quick view of all the techstacks used in the project
pls assign me this issue . i am a gssoc contributor
example of the tech stack:
![image](https://github.com/group-patronage/group-patronage/assets/91930535/165591d5-3127-41ab-a015-1ede9085b290)

**Comment by LakshaySK106** [comment]
Make sure to add these tech stacks: Solidity, React.js, MetaMask, Ethereum, Auth0, ThirdWeb, Tailwind-CSS

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign
