### ISSUE TITLE
adding hover effect 

### ISSUE THREAD

**Issue by mridulsaggi** [group-patronage/group-patronage#36]
i would like to add the hover effect on the lets start button.
pls assign me this issue as gssoc issue

changes i made:
![image](https://github.com/group-patronage/group-patronage/assets/91930535/6b2c4c0f-282e-487b-877f-775548281b18)

**Comment by prishashah17** [comment]
hey, I would like to work upon this. Please assign me this issue.

**Comment by Venkatakrishnan-Ramesh** [comment]
hey @mridulsaggi  . can u kindly give us the update regarding the issue status since it been 2 weeks already or we will reassign

**Comment by Venkatakrishnan-Ramesh** [comment]
Since there is no update from @mridulsaggi , we are giving chance to @prishashah17  kindly update us regularly
