### ISSUE TITLE
Modifications required in CrowdFunding.sol

### ISSUE THREAD

**Issue by shikhar229169** [group-patronage/group-patronage#37]
- To add a check in donateToCampaign() function, which will revert the call if campaign time is exceeded above deadline.
- And the owner of campaign should not be able to donate to his/her own Campaign.

**Comment by LakshaySK106** [comment]
You may work on implementing the functionalities you stated but,

I've reset the previous code and returned back to the initial version. All the modifications made in the code created too many bugs and the contract file wasn't running fine. Make sure to test the code first prior to making the PRs.

**Comment by shikhar229169** [comment]
Can I contact you on any social media, if possible.

**Comment by LakshaySK106** [comment]
Lakshay◥▶_◀◤#4372

My discord username^
