### ISSUE TITLE
no validation at donate campiagn 

### ISSUE THREAD

**Issue by MrSahilShaikh** [group-patronage/group-patronage#38]
If user has no balance or minimum required amount to donate then how can he donate. That's why we need some validation at that function. Due to this transaction will fail.
I want to work under GSSOC'23 . Can you assign me this issue .I am proficient in Solidity and Smart contract.
@LakshaySK106

**Comment by LakshaySK106** [comment]
The transaction should fail in that case. However, in the current version of the contract if the user is running out of the goreliETH it won't be able to make transactions at their end. Hence, no issue?

**Comment by MrSahilShaikh** [comment]
yes but after implementing on other testnet network. it will be the issue.

**Comment by LakshaySK106** [comment]
I don't think so. We can escape the transaction by closing the MetaMask pop-up.
