### ISSUE TITLE
Want to Add Sepolia / polygon Testnet beacuse goerli faucet will deprecating

### ISSUE THREAD

**Issue by MrSahilShaikh** [group-patronage/group-patronage#39]
Description:
Currently, this project relies on the Goerli testnet for testing purposes. However, there are a couple of challenges that affect the usability and efficiency of our testing process.

Current State:

Goerli Faucet Minimum Requirement: The Goerli testnet's faucet requires users to have a minimum of 0.001 ETH on the Ethereum mainnet to receive test ethers. This requirement creates a barrier for users who do not possess any ETH on the mainnet.

Limited Test Ethers: The Goerli testnet currently provides only 0.02 test ethers per day. This allocation is insufficient for testing the project.

Proposed Solution:

Introduce Sepolia/Polygon Testnet: To overcome the limitations mentioned above, we propose adding the Sepolia/polygon testnet as an additional testing option. Sepolia/Polygon offers a more user-friendly experience by providing a higher allocation of test ethers per day, enabling users to conduct extensive testing without being constrained by a limited supply of test ethers.

Eliminate Mainnet ETH Requirement: Unlike the Goerli testnet, the Sepolia/Polygon testnet does not require users to possess any ETH on the Ethereum mainnet. This removes the prerequisite of having a minimum amount of ETH on the mainnet, making it more accessible to all users, especially those who are new to Ethereum testing.

I would like to make the above changes under GSSOC'23. @LakshaySK106

**Comment by LakshaySK106** [comment]
I had no SepoliaETH at the beginning so I've implemented this contract based on Goerli testnet for testing purposes, knowing it's gonna depreciate. Also, getting goreliETH is quite harder than the other ETHs. So, it's good to modify the contract on other testnets as you mentioned for better usability and efficiency. Your solution is totally acceptable. You may work on it.
