### ISSUE TITLE
ADD NEW LOOK TO THE README 

### ISSUE THREAD

**Issue by Ayush-Tibrewal** [group-patronage/group-patronage#4]
I have given your README a completely new look and added simplified text that is highly useful for new contributors. I incorporated the text you provided and made sure it enhances the overall appeal of the document. Please review my changes and let me know if there are any issues. If you have any concerns, feel free to assign me to the relevant issue, and I will address it as soon as possible.

**Comment by Ayush-Tibrewal** [comment]
@amitbatra31 PLEASE ASSIGN ME WITH THE ISSUE

**Comment by LakshaySK106** [comment]
assigned! but make sure to keep the authentic information unchanged

**Comment by Ayush-Tibrewal** [comment]
@LakshaySK106 check the pull request
