### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by VSatwika** [group-patronage/group-patronage#45]
### Description

 - I would like to request the addition of a code of conduct to the repository.

 - Having a code of conduct is essential to establish a welcoming and inclusive environment for all contributors.

 - It provides clear guidelines for expected behavior and helps create a safe and respectful space for collaboration.

 - I am contributing under GSSoC'23. Could this issue be assigned to me?

**Comment by LakshaySK106** [comment]
The file should follow all the contributions guidelines released by GSSoC'23

**Comment by VSatwika** [comment]
> The file should follow all the contributions guidelines released by GSSoC'23

Okay.
