### ISSUE TITLE
[FEATURE]  A better and more attractive Landing page.

### ISSUE THREAD

**Issue by BaibhavTiwari** [group-patronage/group-patronage#48]
### Description

The current landing page of the project is quite simple, would like to create a more attractive landing page, as we know Creating an impactful landing page is the key to engaging visitors and driving conversions. 
From the Screenshot below you can clearly see the current landing page of the project which is more basic and simple, and even it does not show's any connection to the theme of the project.

### Screenshots

![image](https://github.com/group-patronage/group-patronage/assets/75496387/2b545377-c72b-4ac0-9048-5eddf729e22e)

**Comment by LakshaySK106** [comment]
The current UI for the landing page is quite simple and basic which is not making much difference and led to less engagement of the traffic. It should be improved. Assigned you!
