### ISSUE TITLE
Logout Button Not Working.

### ISSUE THREAD

**Issue by aditya9277** [group-patronage/group-patronage#5]
When clicked on logout button, it should log out and redirect to home page to login again. But currently it is redirecting to the localhost website link. something 127.0.0.1:5173
Please assign me this issue and i will fix this issue.

![Issue1](https://github.com/group-patronage/group-patronage/assets/88902527/ad51e2cf-511e-4ad1-8bf8-dcba2535bb21)

**Comment by aditya9277** [comment]
I want to work on this issue.

**Comment by LakshaySK106** [comment]
This issue can be resolved at my end only by just putting the correct URL in the auth0. Thank you for exploring. Try looking into other issues
