### ISSUE TITLE
[DOCS] Adding a about section in Readme to tell the new contributors about the project. [GSSoC'23]

### ISSUE THREAD

**Issue by 1Shubham7** [group-patronage/group-patronage#50]
### Description

The Readme.md directly starts with get started, It does not tell anything about the project. I think an introduction to the project must be given for new contributors coming for the first time.

### Screenshots

This is how the readme starts: 
![readmeissueabout](https://github.com/group-patronage/group-patronage/assets/116020663/f3fa2953-2f36-4e97-8dd4-58ddbcb1193f)

It must start with an intro about the project

### Additional information

Please assign me this issue under GSSoC'23

**Comment by LakshaySK106** [comment]
The intro you are gonna add should be precise, to the point, and relevant. Avoid fake information and features.

**Comment by 1Shubham7** [comment]
@LakshaySK106 thank you for assigning me. I will surely not disappoint you.

**Comment by 1Shubham7** [comment]
@LakshaySK106  Bhaiya. As you said I made it short and didn't add any fake info. Please review and tell me if its good.

**Comment by 1Shubham7** [comment]
Thank you @LakshaySK106 bhaiya
