### ISSUE TITLE
Campaign storage item variable creation outside the loop

### ISSUE THREAD

**Issue by adil-techcode** [group-patronage/group-patronage#52]
### Description

In the getCampaigns function, the variable Campaign storage item is created inside the loop for each iteration. It is recommended to move the variable creation outside the loop to improve gas efficiency and optimize the function.

Please Assign this issue under gssoc'23.

**Comment by LakshaySK106** [comment]
you could raise one issue by listing all the features/bugs in it that you have mentioned in five different issues. Try to minimize the redundancies for better readability unless the features requested are irrelevant.

**Comment by adil-techcode** [comment]
Please Assign this Issue under Gssoc23
