### ISSUE TITLE
[FEATURE] Hiding siderbar in small size screens

### ISSUE THREAD

**Issue by AK4266** [group-patronage/group-patronage#58]
### What is the issue
In the small screen devices the sidebar should be hidden and added to the hamburger menu but the sidebar stays the same and occupying extra space.
### Are you willing to work on the issue?
Yes, Iam willing to work on the issue

### Screenshots

![image](https://github.com/group-patronage/group-patronage/assets/99728079/d6c94275-8c9a-4f4b-87e8-704c3a27ae5f)

**Comment by LakshaySK106** [comment]
Yes, the sidebar should be removed on the smaller screens and the pages should be added to the hamburger menu. You may work on this. However, someone is already assigned to the same issue you may find in the present pull requests(#47) and collaborate with. I'll assign you there just give me a check.

**Comment by AK4266** [comment]
Alright, that's okay with me

**Comment by LakshaySK106** [comment]
Ask at #47 to get assigned. Your name is not rendered in the assignee list.
