### ISSUE TITLE
Improve ReadMe.md 

### ISSUE THREAD

**Issue by VSatwika** [group-patronage/group-patronage#66]
### Description

 - I would like to change styling of some badges in ReadMe.md so it is consistent and gives an overall better look
 - Could this issue be assigned to me under GSSoC'23?

### Screenshots

Before  
<img width="598" alt="bbbadges" src="https://github.com/group-patronage/group-patronage/assets/112561024/bd787fc3-1e97-48b0-b07f-2d3f5abf8f95">

After 
<img width="625" alt="badges" src="https://github.com/group-patronage/group-patronage/assets/112561024/4b6be09a-c588-4980-8649-be603b166611">

**Comment by Venkatakrishnan-Ramesh** [comment]
We appreciate your idea @VSatwika but this issue was already taken down and contribute. We welcome you to work on other issue
