### ISSUE TITLE
[FEATURE] <Adding my contracts>

### ISSUE THREAD

**Issue by Abhinavcode13** [group-patronage/group-patronage#67]
### Description

Adding my smart contracts

### Screenshots

![image](https://github.com/group-patronage/group-patronage/assets/126642111/0f3efaff-08ff-47f6-bf5b-c177b5d00185)

**Comment by Abhinavcode13** [comment]
Please assign this issue to me @LakshaySK106

**Comment by LakshaySK106** [comment]
can you please explain this issue a little?
