### ISSUE TITLE
[FEATURE] Implement lazy loading to the pages

### ISSUE THREAD

**Issue by Avinash905** [group-patronage/group-patronage#68]
### Description

Lazy loading is a technique that can be used to improve the performance of a website by delaying the loading of resources until they are needed. This can help to reduce the initial load time of a page, which can improve the user experience and make the website more responsive.

The benefits of lazy loading include:

- Reduced initial load time
- Improved user experience
- More responsive website

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by LakshaySK106** [comment]
You can work on this issue, you're assigned!
