### ISSUE TITLE
Fixing Logout Functionality 

### ISSUE THREAD

**Issue by codewizard26** [group-patronage/group-patronage#8]
After logging out the user the user is redirected to the localhost url (http://127.0.0.1:5173/) even on the netlify website and not the homepage of the app. Can you please assign me this issue so that I can fix this accordingly. Thanks

**Comment by LakshaySK106** [comment]
This issue can be resolved at my end only by just putting the correct URL in the auth0. Thank you for exploring. Try looking into other issues

**Comment by LakshaySK106** [comment]
This issue can be resolved at my end only by just putting the correct URL in the auth0. Thank you for exploring. Try looking into other issues

**Comment by LakshaySK106** [comment]
This issue can be resolved at my end only by just putting the correct URL in the auth0. Thank you for exploring. Try looking into other issues
