### ISSUE TITLE
[FEATURE] Adding favicon to the site

### ISSUE THREAD

**Issue by Deepanshu0703** [group-patronage/group-patronage#83]
### Description

As I can see there is no icon to the website so i want to add that

### Screenshots

![image](https://github.com/group-patronage/group-patronage/assets/114489502/f4d2335b-e9a3-47b3-a163-b1d1c7b46aa3)

**Comment by Venkatakrishnan-Ramesh** [comment]
@Deepanshu0703 You can add along with your search functionality issue

**Comment by Deepanshu0703** [comment]
ok thanks @Venkatakrishnan-Ramesh
