### ISSUE TITLE
Issue In Website

### ISSUE THREAD

**Issue by Naman1729** [group-patronage/group-patronage#93]
### Screenshots

![image](https://github.com/group-patronage/group-patronage/assets/112473210/6640d3be-9b48-42d6-8fe3-b56351d86162)

**Comment by Naman1729** [comment]
Hey @LakshaySK106 ,
I see frontend on my localhost it working fine but the frontend link which is in this code repo is creating glitches. So there is a need to update the latest front-end in the website

**Comment by LakshaySK106** [comment]
Actually, there is a need to host the latest version of this code but it will be done after the major releases.
